name: Docker Image CI

on:
  push:
    branches: ["master_avoid_workflow"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install Angular CLI
        run: npm install -g @angular/cli@15.2.10

      - name: Run Angular build
        run: ng build --configuration production

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag daneker/ng-node-chat-app-front:latest

      - name: Log in to Docker Hub
        run: docker login --username $DOCKER_USERNAME --password  $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        run: docker push daneker/ng-node-chat-app-front
